---
# file: haproxy/tasks/main.yml
#
# tasks file
#

- include: debug.yml
  when: debug | default(false)
  tags: debug

- include: validation.yml
  tags: validation

- include: install_from_source.yml
  when: haproxy_install == 'source'

- name: ensure haproxy directories are set
  file:
    path="{{ item }}"
    state=directory
    owner="{{ haproxy_user }}"
    group="{{ haproxy_group }}"
    mode=0755
  become: yes
  with_items:
    - "{{ haproxy_dir_conf }}"
    - "{{ haproxy_dir_log }}"

- name: setup haproxy configuration
  template:
    src=etc/haproxy/haproxy.cfg.j2
    dest=/etc/haproxy/haproxy.cfg
    owner=root
    group=root
    mode=0440
  become: yes
  notify: reload haproxy

- name: setup haproxy default environment
  template:
    src=etc/default/haproxy.j2
    dest=/etc/default/haproxy
    owner=root
    group=root
    mode=0640
  become: yes

- name: setup haproxy init script
  template:
    src=etc/init.d/haproxy.j2
    dest=/etc/init.d/haproxy
    owner=root
    group=root
    mode=0755
  become: yes

- name: ensure service is running and enabled to start on boot
  service:
    name=haproxy
    enabled=yes
    state=started
  become: yes

